### ISSUE TITLE
Analog inputs

### ISSUE THREAD

**Issue by OmriShi** [sparkfun/Serial7SegmentDisplay#22]
Hi, 
My name is Omri, and I'm considering the use of your nice S7S for a project I'm working on.

The main goal is using this S7S to display voltage measurements. By considering the 2 analog input pins there is on the breakout board it could be more simple than I thought. 

After reading the "Hardware specifications" I'm a little bit confused.
With the current stat of the breakout and firmware,  can I use the pins to measure the analog voltage?
and if I can, what is the voltage limitation? 

I hope I was clear, thanks for helping

**Comment by bboyho** [comment]
Hi,

I'm sorry for the delay in reply. I was browsing the issues in our GitHub repo when I noticed your question. This is a more technical question and it does not seem to be an issue with the board. It might have been better to have checked in the SparkFun Forums. However, here are some of my thoughts regarding your question if you are still working on the project:

The voltage limitation on the pins depends on the input voltage (Vcc). As stated in the Hardware Overview in the [Wiki](https://github.com/sparkfun/Serial7SegmentDisplay/wiki/Hardware-specifications) and [associated tutorial](https://learn.sparkfun.com/tutorials/using-the-serial-7-segment-display#hardware-overview), it is **3.0V to 5.5V**. Based on the input voltage of the ATmega328P as stated in the [datasheet under the **Absolute Maximum Rating**](http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-7810-Automotive-Microcontrollers-ATmega328P_Datasheet.pdf), that should be about Vcc+/-0.5V on any I/O pin. So if you are powering the device with 3.3V, the limitation on the pins is about 3.3V.

However, using a [voltage divider](https://learn.sparkfun.com/tutorials/voltage-dividers/all#applications), you can theoretically measure higher voltage than your input voltage. I have not tried the method using resistors before but here's one example that I found online => [ [https://startingelectronics.org/articles/arduino/measuring-voltage-with-arduino](https://startingelectronics.org/articles/arduino/measuring-voltage-with-arduino/) ]. You would just need to adjust the default firmware that is loaded on the board to measure and display the values on the 7 segments display. 

Otherwise, try looking at this dedicated [digital 7-segment LED Voltmeter](https://www.sparkfun.com/products/14313).
